# Generated by Django 4.2.6 on 2023-10-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_customer_email_alter_customer_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours de livraison', 'En cours de livraison'), ('Livrée', 'Livrée')], max_length=200, null=True),
        ),
    ]
