# Generated by Django 4.2.6 on 2023-10-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Électronique', 'Électronique'), ('Mode', 'Mode'), ('Alimentation', 'Alimentation')], max_length=15, null=True),
        ),
    ]
